version: '3.2'
services:
  serverdev:
    image: tianon/true
    depends_on: 
      - mssql
      - mailwithdevlogs
    container_name: serverdev_group
  mssql:
    environment: 
      SA_PASSWORD: Password123
      ACCEPT_EULA: 'Y'
    image:  tiendvlp/masa_db:0.1
    container_name: mssqlserver
    restart: always
    volumes:
      - vmssql:/var/opt/mssql     # thư  mục chứa file backup
    ports:
      - "1533:1433"
  backend:
    restart: always
    container_name: masa_backend
    image: tiendvlp/masa_webserver:0.1
    ports:
      - '8081:8080'    # cổng kết nối với tomcat
    volumes:
      - ./masa_backend/target/masa.war:/usr/local/tomcat/webapps/masa.war
      - ./webserver/tomcat/logs:/usr/local/tomcat/logs
  mailwithdevlogs:
    container_name: mailwithdevlogs
    image: tiendvlp/mailwithdevlogs:0.0
    ports: 
      - '8000:8000'
    volumes: 
      - ./maildata:/app/maildata
volumes:
 vmssql:
